### PR TITLE
merge @mickael_istria's commit from Feb 10 into the new target_platforms_for_consumers.adoc [695af23d939b0437e4bde5051bed51fc80a04291] >> sandbox

### PR DESCRIPTION
**Pull request by nickboldt**

### CODE REVIEW

**Comment by mickaelistria** [comment]
I don't find these commit messages very helpful.

**Comment by nickboldt** [comment]
Protip: in place of simply complaining, suggest WHY something needs to be changed, and HOW it could be improved. Provide examples for bonus credit.

**Comment by mickaelistria** [comment]
Why weren't commits cherry-picked? The author and date field of the commit are pretty good to store author name so they don't need to be repeated in comments

**Comment by maxandersen** [comment]
Agreeing with @mickaelistria  and I also don't grok what this PR is about in relation to the big devdoc merge at https://github.com/jbosstools/jbosstools-devdoc/pull/42 ?

shouldn't these just be done as cherry picks to that PR instead of new PR/branch ?

**Comment by nickboldt** [comment]
I saw a commit that was done IN PARALLEL (in master) to all the devdoc stuff in sandbox. Since the plan is to simply force-push from sandbox to master (once we're done here) I figured it was important to pick @mickaelistria 's commit and merge it into the new doc base. 

HOWEVER he updated the .md file and my version is .adoc. 

So, no, I couldn't just cherry-pick. Why do you people get so bogged down in trivial "your process looks wrong" criticisms? 

Why not just say "Nice work! You noticed that extra change in the other branch, and merged it in so it wouldn't be lost" ?

**Comment by nickboldt** [comment]
Coincidentally, if you took the time to read my commit comment, you'd see that the purpose of the commit was, and I quote, " merge @mickael_istria's commit from Feb 10 into the new target_platforms_for_consumers.adoc [695af23]" ... so I was merging his Feb 10 commit into the new adoc file. #seemsLegit

**Comment by robstryker** [comment]
On 04/27/2015 11:57 AM, Nick Boldt wrote:
> Since the plan is to simply force-push from sandbox to master (once 
> we're done here)
The plan is not to simply force-push. The plan is to properly merge in 
the changes. We do not force-push to master. I'm pretty sure this has 
been said a dozen times.

**Comment by nickboldt** [comment]
To clarify the difference between #42 and #43:

#42: "nickboldt wants to merge 5 commits into jbosstools:*master* from nickboldt:sandbox"
#43: "nickboldt wants to merge 4 commits into jbosstools:*sandbox* from nickboldt:sandbox"

Hope that helps.

**Comment by maxandersen** [comment]
okey but jbosstools:sandbox was discontinued very early on. no commits should go in there. hence i'm still confused what the intent is.

**Comment by robstryker** [comment]
>  #43: "nickboldt wants to merge 4 commits into jbosstools:sandbox from nickboldt:sandbox"

There should be no commits into jbt:sandbox ever again. This PR is rejected.

**Comment by maxandersen** [comment]
I deleted the dead sandbox branch to avoid future PR confusions. 
last commit was for 6th jan and seem all to be done before nickboldt:sandbox was setup for the collaboration writing between @nickboldt  and @robstryker 

It can be recovered again if necessary - but seems a fairly dead and unnecessary branch to have around.

**Comment by nickboldt** [comment]
+100, thanks.

**Pull request closed without merging**
