### PR TITLE
JBIDE-19749
use git:// instead of git@ syntax...
...; remove refs to /static/; fix instructions for checkout/branching; promote use of Hub to top of page instead of footnote

### PR DESCRIPTION
**Pull request by nickboldt**

### CODE REVIEW

**Comment by maxandersen** [comment]
no ;) it should be https:// if anything. I thought I already fixed that but seems I missed the ancient git@ syntax. i'll fix that in follow up commit

**Comment by nickboldt** [comment]
Crap, apparently I misquoted your statements here https://github.com/jbosstools/jbosstools-devdoc/pull/42/files#r29133660 when transcribed into https://issues.jboss.org/browse/JBIDE-19749

**Comment by nickboldt** [comment]
Fixed 9079108 with 8ac003b, because https://github.com:jbosstools/jbosstools-target-platforms.git (that second colon implies a port number, not a path segment)

**Comment by maxandersen** [comment]
thanks ;)

**Pull request merged**
