### PR TITLE
JBIDE-19801 - add info on skipTestsOrITests

### PR DESCRIPTION
**Pull request by robstryker**

### CODE REVIEW

**Comment by nickboldt** [comment]
Should these be linked up from the README / index page?

**Comment by robstryker** [comment]
I don't believe testing.adoc needs to be linked up. We just need to migrate the last piece of information out to a proper file.  The testing.adoc file was... 'confused'.   

source/how_to_add_a-test_plugin_or_feature.adoc is already linked up from readme.md and needs no changes.

**Comment by nickboldt** [comment]
so then why not delete testing.adoc, and replace it with a link: to the new page?

**Comment by robstryker** [comment]
I deleted the large section that I moved to the add-a-test file, and added a link to that section from the testing.adoc. 

I'm not willing to delete testing.adoc until a new home is found for the confused RCP paragraph in it. Also, it's wrong to delete files that others (forums, etc) may have links to, so odds are testing.adoc will remain even after a home for the RCP paragraph is found, and serve as a legacy link provider.

**Comment by maxandersen** [comment]
how did you mange to do very few edits but still have the diff show up as if you changed everything  ? thats weird.

**Comment by robstryker** [comment]
I moved a large block of text from one file to a different file.

**Comment by maxandersen** [comment]
btw. testing and testing.adoc have been there since beginning of devdoc - for me it seems the source/how_to_add_a_test_plugin_or_feature.adoc is the one that are misplaced.

**Comment by maxandersen** [comment]
argh i missed the move. I really really don't like that. why do we want stuff about source to contain things related to testing ?

**Comment by robstryker** [comment]
As I said, the 'testing.adoc' file was a bit confused. It wasn't sure whether it was for running tests, or how to STRUCTURE your plugin for optimal running of tests.  Both are different topics. How to run tests, skip tests, skip itests, etc, is relevant for all users.   How to structure your plugin is more of a 'source' category and is not relevant to consumers / people just trying to get up and running.  It's more relevant for core-devs and people making large contributions. 

For how to run the build with / without tests or itests, we already have https://github.com/jbosstools/jbosstools-devdoc/blob/master/building/build_from_commandline.adoc

For example, would martin need to know about adding an itests folder? Or changing the itests pom.xml to fetch different dependencies with certain skip flags?  Probably not.  But I may, from time to time, ask him to check out the code and build it and skip integration tests.

**Comment by maxandersen** [comment]
you are right that source structure description fits better in source.

Running of tests I would expect to be in testing.adoc, not hidden inside building part (not saying we shouldn't mention it in build, but would expect the details and tips to be in testing - but thats separate issue)

**Pull request merged**
