### PR TITLE
JBIDE-11436 initial stub document for how to ...
...use license features; may have to add more steps (eg., removing license.html files and updating build.properties / feature.properties

### PR DESCRIPTION
**Pull request by nickboldt**

### CODE REVIEW

**Comment by mickaelistria** [comment]
I believe it would be worth adding a link to http://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.pde.doc.user%2Ftasks%2Fpde_shared_license.htm

**Comment by nickboldt** [comment]
link added and more steps fleshed out.

**Comment by mickaelistria** [comment]
+1

**Comment by nickboldt** [comment]
Merged.

**Pull request closed without merging**
