### PR TITLE
Combining build options with the how-to-build page

### PR DESCRIPTION
**Pull request by robstryker**

### CODE REVIEW

**Comment by nickboldt** [comment]
No sir, I don't like it. Prefer this in a separate linked file. But if you get enough signatures on this PRtition, I'll merge it. #democracy.

**Comment by maxandersen** [comment]
No big opinion on this, but looks clean enough so my only questions is if any specific reason to do it ?

**Comment by nickboldt** [comment]
So I guess that's one +1 from Rob, one -1 from me, and one 0 from Max. #deadlock

**Comment by robstryker** [comment]
Max gave a +1 on this in private chat.  So I'm going to merge it.

**Comment by maxandersen** [comment]
+1 now that the old links are removed. having the cli options available on the cli page is simpler.

**Pull request merged**
